---
- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_type: t2.micro
    ami: ami-0310483fb2b488153
    region: ap-southeast-2
    key_name: jenk
    vpc_subnet_id: subnet-0ab07036ddce43b63  
    security_group: default
    tag_name: my-plb_instance
  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        region: "{{ region }}"
        security_groups: "{{ security_group }}"
        tags:
          Name: "{{ tag_name }}"
        wait: true
